Create reservation
UTN-FRBA-Mobile/RestoPass pull request #32
Opened 2020-06-29 23:53 UTC by yamilacasarini

2020-06-30 00:11 UTC, juanicabanas requested changes

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/common/restaurant/RestaurantFragment.kt
> +                    }
piola

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepFiveFragment.kt
> +    @SuppressLint("SetTextI18n")
wtf

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepFourFragment.kt
> +
hay una manera mucho más prolija y mantenible que es poner en el strings.xml el texto de esta manera "Reserva para %1$s personas en %2$s...." y después hacer un resources.getString(R.string.[nombre], createReservationViewModel.guests, restauantVIewModel.restaurant.name, ..)

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepFourFragment.kt
> +    }
acordate de cancelar la corrutina acá. para eso esttá el isActive en el try catch tmb

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepOneFragment.kt
> +
te falta cancelar la corrutina

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/reservations/TimesAdapter.kt
> +    var list: List<List<Pair<String, Boolean>>> = listOf()
hermoso

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/service/UserService.kt
> +            else throw e
si el ApiError ya es el localizedMessage, por qué no lo dejás así? APiExcepetion(e.localizedMessage)

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/res/layout/reservation_create_step4.xml
> +        android:scaleType="fitXY" />
"Acordate..." lo dijimos eso, gallega

2020-06-30 00:11 UTC, juanicabanas commented on app/src/main/res/layout/reservation_create_step4.xml
> +        android:scaleType="fitXY" />
Podés...

2020-06-30 01:43 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepFourFragment.kt
> +
No me toma el bold para los valores parametrizables, google y no hay forma que tome el bold, por eso este caso lo hice asi

2020-06-30 01:44 UTC, yamilacasarini commented on app/src/main/res/layout/reservation_create_step4.xml
> +        android:scaleType="fitXY" />
jajajajaj bueno se me chispoteo, ahi lo arreglo

2020-06-30 01:45 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/main/common/restaurant/RestaurantFragment.kt
> +                    }
ta mal?

2020-06-30 01:45 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepFiveFragment.kt
> +    @SuppressLint("SetTextI18n")
ah eso es para que no joda el lint con el stringWithFormat de abajo

2020-06-30 23:12 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/reservations/ReservationCreateStepFourFragment.kt
> +
claro. fijate esta si no queda más lindo 
https://stackoverflow.com/questions/8471711/android-string-format-specify-bold

2020-06-30 23:12 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/common/restaurant/RestaurantFragment.kt
> +                    }
nono, quedó bueno eso

2020-07-01 00:16 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/service/UserService.kt
> +            else throw e
Porque no recibe un string el ApiException sino un objeto ApiError

2020-07-01 00:22 UTC, juanicabanas approved these changes

2020-07-01 00:23 UTC, merged